<script>
/**
 *  # 目标: 进一步理解JS中的错误(Error) 和错误处理
 *   + 1. 错误的类型: 
 *      - Error: 所有错误的父类
 *      - ReferenceError: 引用的变量不存在
 *      - TypeError: 数据值不在其所允许的范围内
 *    + 2. 错误处理
 *      - 捕获错误: try ... catch
 *      - 抛出错误: throw error
 *    + 3. 错误对象
 *      - message属性: 错误相关信息
 *      - stack: 函数调用栈记录信息
**/

// 1. 常见的内置错误
// (1). ReferenceError: 引用的变量不存在
// console.log(a) // ReferenceError: a is not defined

// (2) TypeError: 数据类型不正确
let b = null
// console.log(null.name) // TypeError: Cannot read property 'name' of null
// b = {}
// b.xxx() // TypeError: b.xxx is not a function

// (3). RangeError: 数据值不在其所允许的范围内
function fn() {
  fn()
}
fn() // RangeError: Maximum call stack size exceeded

// (4).  SyntaxError: 语法错误
const c = '''' //SyntaxError: Unexpected string
</script>